// pricing.config.js - Single Source of Truth for all pricing data
// All prices in USD.

export const USD_TO_KZT = 480;

export const AI_MODELS = [
  {
    id: 'gpt-41o',
    name: 'GPT-4.1o (Free/Beta)',
    provider: 'OpenAI',
    inputPer1M: 0.00,
    outputPer1M: 0.00,
    contextTokens: 128000,
    badge: 'FREE',
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    inputPer1M: 2.50,
    outputPer1M: 10.00,
    contextTokens: 128000,
    badge: null,
  },
  {
    id: 'gpt-5-mini',
    name: 'GPT-5 mini',
    provider: 'OpenAI',
    inputPer1M: 0.40,
    outputPer1M: 1.60,
    contextTokens: 128000,
    badge: null,
  },
  {
    id: 'claude-haiku-45',
    name: 'Claude Haiku 4.5',
    provider: 'Anthropic',
    inputPer1M: 0.80,
    outputPer1M: 4.00,
    contextTokens: 200000,
    badge: '0.33x',
  },
  {
    id: 'gemini-25-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'Google',
    inputPer1M: 1.25,
    outputPer1M: 10.00,
    contextTokens: 1000000,
    badge: null,
  },
  {
    id: 'gemini-3-flash',
    name: 'Gemini 3 Flash (Preview)',
    provider: 'Google',
    inputPer1M: 0.075,
    outputPer1M: 0.30,
    contextTokens: 1000000,
    badge: '0.33x',
  },
  {
    id: 'gemini-3-pro',
    name: 'Gemini 3 Pro (Preview)',
    provider: 'Google',
    inputPer1M: 1.25,
    outputPer1M: 5.00,
    contextTokens: 1000000,
    badge: null,
  },
  {
    id: 'gemini-31-pro',
    name: 'Gemini 3.1 Pro (Preview)',
    provider: 'Google',
    inputPer1M: 1.25,
    outputPer1M: 5.00,
    contextTokens: 1000000,
    badge: null,
  },
  {
    id: 'raptor-mini',
    name: 'Raptor mini (Preview)',
    provider: 'PS Cloud',
    inputPer1M: 0.00,
    outputPer1M: 0.00,
    contextTokens: 32000,
    badge: 'FREE',
  },
];

export const CLOUD_PROVIDERS = [
  {
    id: 'firebase-spark',
    name: 'Firebase Spark',
    vendor: 'Firebase',
    flag: 'Firebase',
    tier: 'Free',
    computeType: 'serverless',
    fixedCostUsd: 0,
    invocationFreeLimit: 2000000,
    invocationPricePer1M: 0.40,
    gbSecFreeLimit: 400000,
    gbSecPrice: 0.00001,
    storageFreeGb: 1,
    storagePricePerGb: 0.18,
    egressFreeGb: 10,
    egressPricePerGb: 0.08,
    region: 'Global',
  },
  {
    id: 'firebase-blaze',
    name: 'Firebase Blaze',
    vendor: 'Firebase',
    flag: 'Firebase',
    tier: 'Pay-as-you-go',
    computeType: 'serverless',
    fixedCostUsd: 0,
    invocationFreeLimit: 2000000,
    invocationPricePer1M: 0.40,
    gbSecFreeLimit: 400000,
    gbSecPrice: 0.00001,
    storageFreeGb: 1,
    storagePricePerGb: 0.18,
    egressFreeGb: 10,
    egressPricePerGb: 0.08,
    region: 'Global',
  },
  {
    id: 'aws-lambda',
    name: 'AWS Lambda',
    vendor: 'AWS',
    flag: 'AWS',
    tier: 'Serverless',
    computeType: 'serverless',
    fixedCostUsd: 0,
    invocationFreeLimit: 1000000,
    invocationPricePer1M: 0.20,
    gbSecFreeLimit: 400000,
    gbSecPrice: 0.00001667,
    storageFreeGb: 5,
    storagePricePerGb: 0.023,
    egressFreeGb: 10,
    egressPricePerGb: 0.085,
    region: 'Global',
  },
  {
    id: 'aws-t3micro',
    name: 'AWS EC2 t3.micro',
    vendor: 'AWS',
    flag: 'AWS',
    tier: '2 vCPU / 1 GB RAM',
    computeType: 'vps',
    fixedCostUsd: 7.59,
    storageFreeGb: 5,
    storagePricePerGb: 0.023,
    egressFreeGb: 1024,
    egressPricePerGb: 0.085,
    region: 'us-east-1',
  },
  {
    id: 'aws-t3small',
    name: 'AWS EC2 t3.small',
    vendor: 'AWS',
    flag: 'AWS',
    tier: '2 vCPU / 2 GB RAM',
    computeType: 'vps',
    fixedCostUsd: 15.18,
    storageFreeGb: 5,
    storagePricePerGb: 0.023,
    egressFreeGb: 1024,
    egressPricePerGb: 0.085,
    region: 'us-east-1',
  },
  {
    id: 'gcp-cloudrun',
    name: 'GCP Cloud Run',
    vendor: 'GCP',
    flag: 'GCP',
    tier: 'Serverless',
    computeType: 'serverless',
    fixedCostUsd: 0,
    invocationFreeLimit: 2000000,
    invocationPricePer1M: 0.40,
    gbSecFreeLimit: 400000,
    gbSecPrice: 0.00001,
    storageFreeGb: 5,
    storagePricePerGb: 0.020,
    egressFreeGb: 10,
    egressPricePerGb: 0.08,
    region: 'Global',
  },
  {
    id: 'gcp-e2micro',
    name: 'GCP e2-micro',
    vendor: 'GCP',
    flag: 'GCP',
    tier: '2 vCPU / 1 GB RAM',
    computeType: 'vps',
    fixedCostUsd: 6.11,
    storageFreeGb: 5,
    storagePricePerGb: 0.020,
    egressFreeGb: 10,
    egressPricePerGb: 0.08,
    region: 'us-central1',
  },
  {
    id: 'gcp-e2small',
    name: 'GCP e2-small',
    vendor: 'GCP',
    flag: 'GCP',
    tier: '2 vCPU / 2 GB RAM',
    computeType: 'vps',
    fixedCostUsd: 12.23,
    storageFreeGb: 5,
    storagePricePerGb: 0.020,
    egressFreeGb: 10,
    egressPricePerGb: 0.08,
    region: 'us-central1',
  },
  {
    id: 'azure-b1s',
    name: 'Azure B1s',
    vendor: 'Azure',
    flag: 'Azure',
    tier: '1 vCPU / 1 GB RAM',
    computeType: 'vps',
    fixedCostUsd: 7.59,
    storageFreeGb: 5,
    storagePricePerGb: 0.018,
    egressFreeGb: 5,
    egressPricePerGb: 0.087,
    region: 'East US',
  },
  {
    id: 'azure-b2s',
    name: 'Azure B2s',
    vendor: 'Azure',
    flag: 'Azure',
    tier: '2 vCPU / 4 GB RAM',
    computeType: 'vps',
    fixedCostUsd: 15.18,
    storageFreeGb: 5,
    storagePricePerGb: 0.018,
    egressFreeGb: 5,
    egressPricePerGb: 0.087,
    region: 'East US',
  },
  {
    id: 'do-basic-1gb',
    name: 'DO Basic Droplet 1GB',
    vendor: 'DigitalOcean',
    flag: 'DO',
    tier: '1 vCPU / 1 GB RAM',
    computeType: 'vps',
    fixedCostUsd: 4.00,
    storageFreeGb: 25,
    storagePricePerGb: 0.02,
    egressFreeGb: 1024,
    egressPricePerGb: 0.01,
    region: 'Global',
  },
  {
    id: 'do-basic-2gb',
    name: 'DO Basic Droplet 2GB',
    vendor: 'DigitalOcean',
    flag: 'DO',
    tier: '1 vCPU / 2 GB RAM',
    computeType: 'vps',
    fixedCostUsd: 6.00,
    storageFreeGb: 50,
    storagePricePerGb: 0.02,
    egressFreeGb: 2048,
    egressPricePerGb: 0.01,
    region: 'Global',
  },
  {
    id: 'pscloud-standard',
    name: 'PS Cloud Standard',
    vendor: 'PS Cloud',
    flag: 'KZ',
    tier: '2 vCPU / 4 GB RAM',
    computeType: 'vps',
    fixedCostUsd: 7.80,
    storageFreeGb: 20,
    storagePricePerGb: 0.022,
    egressFreeGb: 100,
    egressPricePerGb: 0.05,
    region: 'Kazakhstan',
    kztPrice: 3500,
  },
  {
    id: 'qaztelecom-lite',
    name: 'Qaztelecom VPS Lite',
    vendor: 'Qaztelecom',
    flag: 'KZ',
    tier: '1 vCPU / 1 GB RAM',
    computeType: 'vps',
    fixedCostUsd: 4.44,
    storageFreeGb: 20,
    storagePricePerGb: 0.022,
    egressFreeGb: 100,
    egressPricePerGb: 0.05,
    region: 'Kazakhstan',
    kztPrice: 2000,
  },
  {
    id: 'qaztelecom-standard',
    name: 'Qaztelecom VPS Standard',
    vendor: 'Qaztelecom',
    flag: 'KZ',
    tier: '2 vCPU / 2 GB RAM',
    computeType: 'vps',
    fixedCostUsd: 8.89,
    storageFreeGb: 20,
    storagePricePerGb: 0.022,
    egressFreeGb: 100,
    egressPricePerGb: 0.05,
    region: 'Kazakhstan',
    kztPrice: 4000,
  },
];
