// calculator.js — Core math engine (matches SSOT Section 4 exactly)
import { saveSession } from "../services/session.service";
import { USD_TO_KZT } from '../config/pricing.config.js';

/**
 * Calculate AI API cost
 */
export function calcAiCost(model, dailyMessages, tokensIn, tokensOut) {
  if (dailyMessages <= 0) throw new Error('Messages must be > 0');
  const monthly = dailyMessages * 30;
  const costIn = (monthly * tokensIn / 1_000_000) * model.inputPer1M;
  const costOut = (monthly * tokensOut / 1_000_000) * model.outputPer1M;
  return +(costIn + costOut).toFixed(6);
}

/**
 * Calculate compute / hosting cost
 */
export function calcComputeCost(provider, dailyMessages, execMs = 800, memGb = 0.25) {
  if (provider.computeType === 'vps') {
    return provider.fixedCostUsd;
  }
  // Serverless
  const invocations = dailyMessages * 2 * 30;
  const gbSeconds = invocations * (execMs / 1000) * memGb;

  const freeInv = provider.invocationFreeLimit ?? 2_000_000;
  const freeGbSec = provider.gbSecFreeLimit ?? 400_000;

  const costInv = Math.max(0, invocations - freeInv) / 1_000_000 * (provider.invocationPricePer1M ?? 0.40);
  const costGbSec = Math.max(0, gbSeconds - freeGbSec) * (provider.gbSecPrice ?? 0.00001);

  return +(costInv + costGbSec).toFixed(6);
}

/**
 * Calculate storage cost
 */
export function calcStorageCost(provider, dailyMessages, monthlyUsers) {
  const monthly = dailyMessages * 30;
  const storedBytes =
  monthly * 25000 +        // messages + embeddings
  monthlyUsers * 5000000;  // profiles + media
  const storedGb = storedBytes / 1_073_741_824;
  const billable = Math.max(0, storedGb - (provider.storageFreeGb ?? 1));
  return +(billable * (provider.storagePricePerGb ?? 0.18)).toFixed(6);
}

/**
 * Calculate bandwidth/egress cost
 */
export function calcBandwidthCost(provider, dailyMessages, monthlyUsers) {
  const monthly = dailyMessages * 30;
  const msgEgressGb = monthly * 8000 / 1_073_741_824;
  const assetEgressGb = monthlyUsers * 2 / 1024;
  const totalGb = msgEgressGb + assetEgressGb;

  const freeGb = provider.egressFreeGb ?? 10;
  const billable = Math.max(0, totalGb - freeGb);
  const pricePerGb = provider.egressPricePerGb ?? 0.08;

  // Tiered pricing for AWS CloudFront (1TB -> 0.085, then 0.07)
  let cost = 0;
  if (provider.vendor === 'AWS' && billable > 1024) {
    cost = 1024 * 0.085 + (billable - 1024) * 0.070;
  } else {
    cost = billable * pricePerGb;
  }
  return +cost.toFixed(6);
}

/**
 * Main orchestrator — calculates full breakdown
 */
export function calculateTotal(params) {
  const { model, provider, dailyMessages, monthlyUsers, tokensIn, tokensOut, execMs, memGb } = params;

  if (!dailyMessages || dailyMessages <= 0) throw new Error('Messages must be > 0');

  if (tokensIn > (model.contextTokens ?? 128000)) {
    console.warn(`Input tokens (${tokensIn}) exceed model context (${model.contextTokens})`);
  }

  const aiCost = calcAiCost(model, dailyMessages, tokensIn, tokensOut);
  const computeCost = calcComputeCost(provider, dailyMessages, execMs, memGb);
  const storageCost = calcStorageCost(provider, dailyMessages, monthlyUsers);
  const bandwidthCost = calcBandwidthCost(provider, dailyMessages, monthlyUsers);

  const total = +(aiCost + computeCost + storageCost + bandwidthCost).toFixed(4);
  const monthly = dailyMessages * 30;

  return {
    provider: provider.id,
    providerName: provider.name,
    providerFlag: provider.flag,
    model: model.id,
    modelName: model.name,
    totalUsd: total,
    totalKzt: Math.round(total * USD_TO_KZT),
    perMessageUsd: +(total / monthly).toFixed(8),
    monthlyMessages: monthly,
    breakdown: {
      aiCost,
      computeCost,
      storageCost,
      bandwidthCost,
    },
  };
}

/**
 * Run calculation across ALL providers for comparison
 */
export function calculateAllProviders(params, providers) {
  return providers.map(provider => {
    try {
      return calculateTotal({ ...params, provider });
    } catch {
      return null;
    }
  }).filter(Boolean).sort((a, b) => a.totalUsd - b.totalUsd);
}

/**
 * Export results to CSV string
 */
export function exportToCsv(results, params) {
  const header = 'Provider,Model,AI Cost ($),Compute ($),Storage ($),Bandwidth ($),Total ($/mo),Per Message ($),Total (KZT)';
  const rows = results.map(r =>
    `"${r.providerName}","${r.modelName}",${r.breakdown.aiCost},${r.breakdown.computeCost},${r.breakdown.storageCost},${r.breakdown.bandwidthCost},${r.totalUsd},${r.perMessageUsd},${r.totalKzt}`
  );
  const meta = `\n"Generated by CFO Bot","Daily Messages: ${params.dailyMessages}","Monthly Users: ${params.monthlyUsers}"`;
  return [header, ...rows, meta].join('\n');
}
